Fix slang's slangpy CI testing across versions
Relates to #8828

Whenever you're testing, say, a slang 2025.22 release using slangpy
built against slang 2025.21.2, you need to account for the library
name difference when attempting to overwrite the slang libraries in
the locally installed python site-package.

This change plugs a hole in testing that could occur in the time
between when a new slang release is made, and when an updated slangpy
release is pushed to PyPI that uses that new slang release.

diff --git a/.github/workflows/ci-slang-test.yml b/.github/workflows/ci-slang-test.yml
--- a/.github/workflows/ci-slang-test.yml
+++ b/.github/workflows/ci-slang-test.yml
@@ -204,6 +204,20 @@ jobs:
           if [[ "${{ inputs.os }}" == "windows" ]]; then
             cp "$bin_dir"/slang*.dll "$SITE_PACKAGES/slangpy/" || { echo "Failed to copy library files"; exit 1; }
           else
+            # This is kind of awkward because the version numbers might be
+            # different between the old libslang-compiler and the new one, so
+            # we need to make sure we overwrite the old one. This logic also
+            # tries to avoid making assumptions about filename extension due to
+            # differences in macos and Linux conventions.
+
+            # There should be only one libslang-compiler library present; the
+            # one that slangpy linked to.
+            OLD_SLANGLIB=$(find "$SITE_PACKAGES/slangpy/" -type f -name libslang-compiler.\*)
+            # Find the name of the new libslang-compiler library via symlink
+            NEW_SLANGLIB=$(find "$lib_dir" -type l -name libslang-compiler.\* | xargs realpath)
+            cp "$OLD_SLANGLIB" "$NEW_SLANGLIB" || { echo "Failed to copy main library file"; exit 1; }
+
+            # Copy the rest of the library files
             cp "$lib_dir"/libslang*.* "$SITE_PACKAGES/slangpy/" || { echo "Failed to copy library files"; exit 1; }
           fi
 
