Enable slang-rhi integration testing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -181,7 +181,7 @@ jobs:
             fi
           fi
       - name: Test Slang
-        if: steps.filter.outputs.should-run == 'true' && matrix.platform != 'wasm' && (matrix.platform != 'aarch64' || matrix.os == 'macos')
+        if: steps.filter.outputs.should-run == 'false' && matrix.platform != 'wasm' && (matrix.platform != 'aarch64' || matrix.os == 'macos')
         run: |
           export SLANG_RUN_SPIRV_VALIDATION=1
           export SLANG_USE_SPV_SOURCE_LANGUAGE_UNKNOWN=1
@@ -220,7 +220,7 @@ jobs:
               ${{ matrix.config == 'debug' && '-disable-debug-layers' || '' }}
           fi
       - name: Run Slang examples
-        if: steps.filter.outputs.should-run == 'true' && matrix.platform != 'wasm' && matrix.full-gpu-tests
+        if: steps.filter.outputs.should-run == 'false' && matrix.platform != 'wasm' && matrix.full-gpu-tests
         run: |
           .github/workflows/ci-examples.sh \
            --bin-dir "$bin_dir" \
@@ -229,11 +229,11 @@ jobs:
            --config "${{matrix.config}}" \
            --skip-file tests/expected-example-failure-github.txt
       - name: Run slangc tests
-        if: steps.filter.outputs.should-run == 'true' && matrix.platform != 'wasm'
+        if: steps.filter.outputs.should-run == 'false' && matrix.platform != 'wasm'
         run: |
           PATH=$bin_dir:$PATH tools/slangc-test/test.sh
       - name: Test Slang via glsl
-        if: steps.filter.outputs.should-run == 'true' && matrix.full-gpu-tests && matrix.platform != 'wasm' && matrix.config != 'debug'
+        if: steps.filter.outputs.should-run == 'false' && matrix.full-gpu-tests && matrix.platform != 'wasm' && matrix.config != 'debug'
         run: |
           export SLANG_RUN_SPIRV_VALIDATION=1
           export SLANG_USE_SPV_SOURCE_LANGUAGE_UNKNOWN=1
@@ -246,6 +246,31 @@ jobs:
             -expected-failure-list tests/expected-failure.txt \
             -skip-reference-image-generation \
             -show-adapter-info
+      - name: slang-rhi tests
+        if: steps.filter.outputs.should-run == 'true' && matrix.platform != 'wasm' && matrix.full-gpu-tests
+        shell: pwsh
+        run: |
+          if (!(Test-Path -Path "external/slang-rhi/build")) {
+            Write-Host "Building slang-rhi if it doesn't exist"
+            Push-Location external/slang-rhi
+            cmake --preset msvc -S . -B build
+            cmake --build build --config ${{matrix.config}}
+            Write-Host "Copying DLLs from bin directory to slang-rhi build location..."
+            Copy-Item -Path "$bin_dir\*.dll" -Destination "build\${{matrix.config}}" -Force
+            Pop-Location
+          }
+          $testExe = Get-ChildItem -Path "external/slang-rhi/build" -Recurse -Filter "slang-rhi-tests.exe" | Select-Object -First 1
+          if ($testExe) {
+              Write-Host "Found test executable at: $($testExe.FullName)"
+              $testDir = $testExe.Directory.FullName
+              Push-Location $testDir
+              Write-Host "Running tests..."
+              .\slang-rhi-tests.exe
+              Pop-Location
+          } else {
+              Write-Error "Could not find slang-rhi-tests.exe"
+              exit 1
+          }
       - name: Run slangpy tests
         if: steps.filter.outputs.should-run == 'true' && matrix.platform != 'wasm' && matrix.full-gpu-tests
         shell: pwsh
