notarize on osx

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -80,18 +80,83 @@ jobs:
           cmake --preset default --fresh \
             -DSLANG_GENERATORS_PATH=build-platform-generators/bin \
             -DSLANG_ENABLE_EXAMPLES=OFF \
-            -DSLANG_SLANG_LLVM_FLAVOR=DISABLE
+            -DSLANG_SLANG_LLVM_FLAVOR=$(
+              [[ ${{matrix.build-llvm}} = "true" ]] && echo "USE_SYSTEM_LLVM" || echo "DISABLE")
 
-          cmake --workflow --preset "${{matrix.config}}"
+          cmake --build --preset "${{matrix.config}}"
+
+      - name: Sign and notarize binaries
+        if: matrix.os == 'macos'
+        id: notarize
+        env:
+          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
+          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
+          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+          IDENTITY_ID: d6ada82a113e4204aaad914e1013e9548ffd30d0
+          AC_PASSWORD: ${{secrets.APPLE_ID_PASSWORD}}
+          AC_PROVIDER: ${{secrets.APPLE_ID_PPOVIDER}}
+          AC_USERNAME: ${{secrets.APPLE_ID_USERNAME}}
+        run: |
+          brew install Bearer/tap/gon
+          security find-identity -v
+          brew install coreutils
+
+          # create variables
+          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
+          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+
+          # import certificate and provisioning profile from secrets
+          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
+
+          # create temporary keychain
+          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+
+          # import certificate to keychain
+          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+          security list-keychain -d user -s $KEYCHAIN_PATH
+
+          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${KEYCHAIN_PASSWORD} $KEYCHAIN_PATH
+
+          signedFiles
+          find "build/$Config/{bin,lib}" -type f -perm +111 \
+            | xargs codesign --force --options runtime -s "${IDENTITY_ID}" -v
+
+          binaries=(
+            "build/${Config}/lib/libslang.dylib"
+            "build/${Config}/lib/libslang-rt.dylib"
+            "build/${Config}/lib/libslang-glslang.dylib"
+            "build/${Config}/lib/libslang-llvm.dylib"
+            "build/${Config}/lib/libgfx.dylib"
+            "build/${Config}/bin/slangd"
+            "build/${Config}/bin/slangc"
+          )
+          for b in "${binaries[@]}"; do
+            if [[ -f "$b" ]]; then
+              7z a "slang-macos-dist.zip" "${existing_files[@]}"
+            fi
+          done
+
+          timeout 1000 gon ./extras/macos-notarize.json
+
+          cp slang-macos-dist.zip "slang-macos-dist-${{matrix.platform}}.zip"
+          echo "SLANG_NOTARIZED_DIST=slang-macos-dist-${{matrix.platform}}.zip" >> $GITHUB_OUTPUT
 
       - name: File check
         run: |
           find build/dist-release ! -iname '*.md' ! -iname '*.h' -type f | xargs file
+          if [ "${{matrix.os}}" = "macos" ]; then
+            find build/dist-release ! -iname '*.md' ! -iname '*.h' -type f
+              | xargs codesign --verify --verbose=2
+              || echo "code signing failed"
+          fi
 
       - name: Package Slang
         id: package
         run: |
           # For the release, also generate a tar.gz file
+          cpack --preset release -G ZIP
           cpack --preset release -G TGZ
 
           triggering_ref=${{ github.ref_name }}
@@ -112,5 +177,6 @@ jobs:
           files: |
             ${{ steps.package.outputs.SLANG_BINARY_ARCHIVE_ZIP }}
             ${{ steps.package.outputs.SLANG_BINARY_ARCHIVE_TAR }}
+            ${{ steps.notarize.outputs.SLANG_NOTARIZED_DIST }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
